/*
Programmer: Siddhi Patel
Date: April 11, 2025
Program Name: Matching Game
Program Description: This program uses arrays to stimulate a matching game.
* A grid of cards will be displayed and the user is to select 2 cards at a time
* looking for matching cards. The goal of this game is to see how quickly
* the user can find all the matches. The game can be played again multiple times by using the play button.
 */
package matchinggame;
import java.util.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Siddhi
 */
public class MatchingGame extends javax.swing.JFrame {
    
//arrayLists to hold cards in the original list, in an image list and cards set at random positions
ArrayList <String> cards = new ArrayList(); //for the matching cards (match IDs)
ArrayList <ImageIcon> cardImages = new ArrayList(); //for the card images
ArrayList<Integer> indexes = new ArrayList(); //for the card positions

//ImageIcon variables to hold and change pictures for matching
ImageIcon aL = new ImageIcon("audiLogo.png");
ImageIcon a = new ImageIcon("audiR8.jpg");
ImageIcon bL = new ImageIcon("bmwLogo.jpg");
ImageIcon b = new ImageIcon("bmwM4.jpg");
ImageIcon cL = new ImageIcon("buggatiLogo.jpg");
ImageIcon c = new ImageIcon("buggati.jpg");
ImageIcon dL = new ImageIcon("ferrariLogo.jpg");
ImageIcon d = new ImageIcon("ferrari.jpg");
ImageIcon eL = new ImageIcon("jaguarLogo.jpg");
ImageIcon e = new ImageIcon("jaguar.jpg");
ImageIcon fL = new ImageIcon("lamborginiLogo.png");
ImageIcon f = new ImageIcon("lamborgini.jpg");
ImageIcon gL = new ImageIcon("mcClarenLogo.jpg");
ImageIcon g = new ImageIcon("mcClaren.jpg");
ImageIcon hL = new ImageIcon("mercedesLogo.jpg");
ImageIcon h = new ImageIcon("mercedesbenz.jpg");
ImageIcon iL = new ImageIcon("mustangLogo.jpg");
ImageIcon i = new ImageIcon("mustang.jpg");
ImageIcon jL = new ImageIcon("porscheLogo.jpg");
ImageIcon j = new ImageIcon("porsche911.jpg");
ImageIcon back = new ImageIcon("cardback.png");
ImageIcon done = new ImageIcon("done.png");

int count, c1, c2; //variables for counting pairs and checking matches
int cardsLeft = 20; //variable for counting unmatched cards left
int[] change = new int[20]; //array for the status of the cards (hidden, flipped, matched)
int[] flipped = new int[2]; //array to hold the indexes of the flipped cards
    
    /**
     * Creates new form MatchingGamesPractice
     */
    public MatchingGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        Card1 = new javax.swing.JButton();
        Card2 = new javax.swing.JButton();
        Card3 = new javax.swing.JButton();
        Card4 = new javax.swing.JButton();
        Card5 = new javax.swing.JButton();
        Card6 = new javax.swing.JButton();
        Card7 = new javax.swing.JButton();
        Card8 = new javax.swing.JButton();
        Card9 = new javax.swing.JButton();
        Card10 = new javax.swing.JButton();
        Card11 = new javax.swing.JButton();
        Card12 = new javax.swing.JButton();
        Card13 = new javax.swing.JButton();
        Card14 = new javax.swing.JButton();
        Card15 = new javax.swing.JButton();
        Card16 = new javax.swing.JButton();
        Card17 = new javax.swing.JButton();
        Card18 = new javax.swing.JButton();
        Card19 = new javax.swing.JButton();
        Card20 = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnGuessAgain = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        Instructions = new javax.swing.JTextField();
        TopMenu = new javax.swing.JMenuBar();
        FileOption = new javax.swing.JMenu();
        EditOption = new javax.swing.JMenu();
        HelpOption = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matching Game");

        mainTitle.setFont(new java.awt.Font("Stencil", 0, 32)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(163, 175, 242));
        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitle.setText("Matching Game");

        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card1MouseClicked(evt);
            }
        });

        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card2MouseClicked(evt);
            }
        });

        Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card3MouseClicked(evt);
            }
        });

        Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card4MouseClicked(evt);
            }
        });

        Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card5MouseClicked(evt);
            }
        });

        Card6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card6MouseClicked(evt);
            }
        });

        Card7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card7MouseClicked(evt);
            }
        });

        Card8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card8MouseClicked(evt);
            }
        });

        Card9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card9MouseClicked(evt);
            }
        });

        Card10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card10MouseClicked(evt);
            }
        });

        Card11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card11MouseClicked(evt);
            }
        });

        Card12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card12MouseClicked(evt);
            }
        });

        Card13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card13MouseClicked(evt);
            }
        });

        Card14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card14MouseClicked(evt);
            }
        });

        Card15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card15MouseClicked(evt);
            }
        });

        Card16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card16MouseClicked(evt);
            }
        });

        Card17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card17MouseClicked(evt);
            }
        });

        Card18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card18MouseClicked(evt);
            }
        });

        Card19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card19MouseClicked(evt);
            }
        });

        Card20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggame/cardback.png"))); // NOI18N
        Card20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card20MouseClicked(evt);
            }
        });

        btnPlay.setBackground(new java.awt.Color(163, 240, 208));
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnGuessAgain.setBackground(new java.awt.Color(190, 226, 249));
        btnGuessAgain.setText("Guess Again");
        btnGuessAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessAgainActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        Instructions.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Instructions.setText("Click the Play button to start. Make sure to click Guess Again after each guess.");

        FileOption.setText("File");
        TopMenu.add(FileOption);

        EditOption.setText("Edit");
        TopMenu.add(EditOption);

        HelpOption.setText("Help");
        TopMenu.add(HelpOption);

        setJMenuBar(TopMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnExit)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Card6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Card10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Card14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Card3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Card4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGuessAgain))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Card5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Card7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Card8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Card9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Card11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Card15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Card13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Card12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Card16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Card17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Card19, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Card18, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Card20, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(mainTitle)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(mainTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Card17, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(Card19, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Card20, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Card5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Card9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Card13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Card10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Card6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Card14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Card18, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Card7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card15, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Card8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card16, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuessAgain)
                            .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(Instructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addGap(13, 13, 13))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); //exits the application
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        /*Set the change array */
        for(int z= 0; z<=19; z++){
            change[z] = 1; //sets all cards to hidden
        }
        
        /*Clear the card position array, the card images array, and the indexes array*/
        cards.clear();
        cardImages.clear();
        indexes.clear();
        
        /*Creates and sets an array to hold all the image icons for each card */
        ImageIcon[] imageIcons = { a, aL, b, bL, c, cL, d, dL, e, eL, f, fL, g, gL, h, hL, i, iL, j, jL };
    
       /*Set the index array*/
        for (int i = 0; i < 20; i++) {
            indexes.add(i);
        }

        Collections.shuffle(indexes); //Shuffle the indexes for the positions of the cards

        //Fills the cards and cardImages array lists using the shuffled indexes
        for (int i = 0; i < 20; i++) {
            int imgIndex = indexes.get(i); //get an image index for each card
            cardImages.add(imageIcons[imgIndex]); // add card images in random positions
            cards.add(String.valueOf(imgIndex / 2)); // add match IDs: 0–9 (two matching cards will have the same matchID)
        } 

    /*Resets the card faces*/
        Card1.setIcon(back);
        Card2.setIcon(back);
        Card3.setIcon(back);
        Card4.setIcon(back);
        Card5.setIcon(back);
        Card6.setIcon(back);
        Card7.setIcon(back);
        Card8.setIcon(back);
        Card9.setIcon(back);
        Card10.setIcon(back);
        Card11.setIcon(back);
        Card12.setIcon(back);
        Card13.setIcon(back);
        Card14.setIcon(back);
        Card15.setIcon(back);
        Card16.setIcon(back);
        Card17.setIcon(back);
        Card18.setIcon(back);
        Card19.setIcon(back);
        Card20.setIcon(back);

        /*Resets the game conditions*/
        count = 0; //reset count to zero
        cardsLeft = 20; //resets the number of unmatched cards
        Instructions.setText("Click the Play button to start. Make sure to click Guess Again after each guess."); //resets the instructions
    }//GEN-LAST:event_btnPlayActionPerformed

    private void Card1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card1MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[0] != 1 || count == 2){
            return;
        }
        
        Card1.setIcon(cardImages.get(0)); //sets the card to a random image using its index
        change[0] = 0; //sets the card to flipped
        String temp = cards.get(0); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp); 
            flipped[0] = 0;  
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 0;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card1MouseClicked
        
    private void Card2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card2MouseClicked
       /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[1] != 1 || count == 2){
            return;
        }
        
        Card2.setIcon(cardImages.get(1)); //sets the card to a random image using its index
        change[1] = 0; //sets the card to flipped
        String temp = cards.get(1); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp); 
            flipped[0] = 1;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 1;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card2MouseClicked

    private void Card3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card3MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[2] != 1 || count == 2){
            return;
        }
        
        Card3.setIcon(cardImages.get(2)); //sets the card to a random image using its index
        change[2] = 0; //sets the card to flipped
        String temp = cards.get(2); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 2;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 2;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card3MouseClicked

    private void Card4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card4MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[3] != 1 || count == 2){
            return;
        }
        
        Card4.setIcon(cardImages.get(3)); //sets the card to a random image using its index
        change[3] = 0; //sets the card to flipped
        String temp = cards.get(3); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 3;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 3;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card4MouseClicked

    private void Card5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card5MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[4] != 1 || count == 2){
            return;
        }
        
        Card5.setIcon(cardImages.get(4)); //sets the card to a random image using its index
        change[4] = 0; //sets the card to flipped
        String temp = cards.get(4); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 4;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 4;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card5MouseClicked

    private void Card6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card6MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[5] != 1 || count == 2){
            return;
        }
        
        Card6.setIcon(cardImages.get(5)); //sets the card to a random image using its index
        change[5] = 0; //sets the card to flipped
        String temp = cards.get(5); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 5;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 5;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card6MouseClicked

    private void Card7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card7MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[6] != 1 || count == 2){
            return;
        }
        
        Card7.setIcon(cardImages.get(6)); //sets the card to a random image using its index
        change[6] = 0; //sets the card to flipped
        String temp = cards.get(6); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 6;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 6;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card7MouseClicked

    private void Card8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card8MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[7] != 1 || count == 2){
            return;
        }
        
        Card8.setIcon(cardImages.get(7)); //sets the card to a random image using its index
        change[7] = 0; //sets the card to flipped
        String temp = cards.get(7); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 7;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 7;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card8MouseClicked

    private void Card9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card9MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[8] != 1 || count == 2){
            return;
        }
        
        Card9.setIcon(cardImages.get(8)); //sets the card to a random image using its index
        change[8] = 0; //sets the card to flipped
        String temp = cards.get(8); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 8;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 8;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card9MouseClicked

    private void Card10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card10MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[9] != 1 || count == 2){
            return;
        }
        
        Card10.setIcon(cardImages.get(9)); //sets the card to a random image using its index
        change[9] = 0; //sets the card to flipped
        String temp = cards.get(9); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 9;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 9;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card10MouseClicked

    private void Card11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card11MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[10] != 1 || count == 2){
            return;
        }
        
        Card11.setIcon(cardImages.get(10)); //sets the card to a random image using its index
        change[10] = 0; //sets the card to flipped
        String temp = cards.get(10); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 10;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 10;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card11MouseClicked

    private void Card12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card12MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[11] != 1 || count == 2){
            return;
        }
        
        Card12.setIcon(cardImages.get(11)); //sets the card to a random image using its index
        change[11] = 0; //sets the card to flipped
        String temp = cards.get(11); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 11;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 11;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card12MouseClicked

    private void Card13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card13MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[12] != 1 || count == 2){
            return;
        }
        
        Card13.setIcon(cardImages.get(12)); //sets the card to a random image using its index
        change[12] = 0; //sets the card to flipped
        String temp = cards.get(12); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 12;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 12;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card13MouseClicked

    private void Card14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card14MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[13] != 1 || count == 2){
            return;
        }
        
        Card14.setIcon(cardImages.get(13)); //sets the card to a random image using its index
        change[13] = 0; //sets the card to flipped
        String temp = cards.get(13); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 13;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 13;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card14MouseClicked

    private void Card15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card15MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[14] != 1 || count == 2){
            return;
        }
        
        Card15.setIcon(cardImages.get(14)); //sets the card to a random image using its index
        change[14] = 0; //sets the card to flipped
        String temp = cards.get(14); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 14;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 14;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card15MouseClicked

    private void Card16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card16MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[15] != 1 || count == 2){
            return;
        }
        
        Card16.setIcon(cardImages.get(15)); //sets the card to a random image using its index
        change[15] = 0; //sets the card to flipped
        String temp = cards.get(15); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 15;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 15;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card16MouseClicked

    private void Card17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card17MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[16] != 1 || count == 2){
            return;
        }
        
        Card17.setIcon(cardImages.get(16)); //sets the card to a random image using its index
        change[16] = 0; //sets the card to flipped
        String temp = cards.get(16); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 16;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 16;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card17MouseClicked

    private void Card18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card18MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[17] != 1 || count == 2){
            return;
        }
        
        Card18.setIcon(cardImages.get(17)); //sets the card to a random image using its index
        change[17] = 0; //sets the card to flipped
        String temp = cards.get(17); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 17;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 17;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card18MouseClicked

    private void Card19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card19MouseClicked
        /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[18] != 1 || count == 2){
            return;
        }
        
        Card19.setIcon(cardImages.get(18)); //sets the card to a random image using its index
        change[18] = 0; //sets the card to flipped
        String temp = cards.get(18); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 18;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 18;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card19MouseClicked

    private void Card20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card20MouseClicked
         /*If the card is already flipped or if two cards are already flipped up, it will simply return*/
        if(change[19] != 1 || count == 2){
            return;
        }
        
        Card20.setIcon(cardImages.get(19)); //sets the card to a random image using its index
        change[19] = 0; //sets the card to flipped
        String temp = cards.get(19); //gets the match ID of the card using its index
        
        /*Sets card to its match Id and adds the card index to the flipped array*/
        if (count == 0) { //if card flipped is the first one
            c1 = Integer.parseInt(temp);
            flipped[0] = 19;
        } 
        else if (count == 1) { //if card flipped is the second one
            c2 = Integer.parseInt(temp);
            flipped[1] = 19;
        }
        count++; //update the number of cards flipped
    }//GEN-LAST:event_Card20MouseClicked

    private void btnGuessAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessAgainActionPerformed
        if (count != 2){ //if two cards are not flipped, nothing will change
            return;
        }
        int x1 = flipped [0]; //index of first flipped card
        int x2 = flipped [1]; //index of second flipped card
        
        if(c1 == c2){ // if the cards match, change the card images to done
            //first card flipped
            if(x1 == 0){
                Card1.setIcon(done);
            }
            else if (x1 == 1){
                Card2.setIcon(done);
            }
            else if (x1 == 2){
                Card3.setIcon(done);
            }
            else if (x1 == 3){
                Card4.setIcon(done);
            }
            else if (x1 == 4){
                Card5.setIcon(done);
            }
            else if (x1 == 5){
                Card6.setIcon(done);
            }
            else if (x1 == 6){
                Card7.setIcon(done);
            }
            else if (x1 == 7){
                Card8.setIcon(done);
            }
            else if (x1 == 8){
                Card9.setIcon(done);
            }
            else if (x1 == 9){
                Card10.setIcon(done);
            }
            else if (x1 == 10){
                Card11.setIcon(done);
            }
            else if (x1 == 11) {
                Card12.setIcon(done);
            }
            else if (x1 == 12) {
                Card13.setIcon(done);
            }
            else if (x1 == 13) {
                Card14.setIcon(done);
            }
            else if (x1 == 14) {
                Card15.setIcon(done);
            }
            else if (x1 == 15) {
                Card16.setIcon(done);
            }
            else if (x1 == 16) {
                Card17.setIcon(done);
            }
            else if (x1 == 17) {
                Card18.setIcon(done);
            }
            else if (x1 == 18) {
                Card19.setIcon(done);
            }
            else if (x1 == 19) {
                Card20.setIcon(done);
            }
            
            //second card flipped
            if(x2 == 0){
                Card1.setIcon(done);
            }
            else if (x2 == 1){
                Card2.setIcon(done);
            }
            else if (x2 == 2){
                Card3.setIcon(done);
            }
            else if (x2 == 3){
                Card4.setIcon(done);
            }
            else if (x2 == 4){
                Card5.setIcon(done);
            }
            else if (x2 == 5){
                Card6.setIcon(done);
            }
            else if (x2 == 6){
                Card7.setIcon(done);
            }
            else if (x2 == 7){
                Card8.setIcon(done);
            }
            else if (x2 == 8){
                Card9.setIcon(done);
            }
            else if (x2 == 9){
                Card10.setIcon(done);
            }
            else if (x2 == 10){
                Card11.setIcon(done);
            }
            else if (x2 == 11) {
                Card12.setIcon(done);
            }
            else if (x2 == 12) {
                Card13.setIcon(done);
            }
            else if (x2 == 13) {
                Card14.setIcon(done);
            }
            else if (x2 == 14) {
                Card15.setIcon(done);
            }
            else if (x2 == 15) {
                Card16.setIcon(done);
            }
            else if (x2 == 16) {
                Card17.setIcon(done);
            }
            else if (x2 == 17) {
                Card18.setIcon(done);
            }
            else if (x2 == 18) {
                Card19.setIcon(done);
            }
            else if (x2 == 19) {
                Card20.setIcon(done);
            }
            
            /*Change the card indexes to matched*/
            change[x1] = 2;
            change[x2] = 2;
            
            cardsLeft -= 2; //update cards left after a match is made
            if (cardsLeft == 0) { //if all cards are matched
                Instructions.setText("Congratulations! You matched all the cards!"); //update instructions to congratulations
            }
        }
        else{ // if the cards don't match, reset the card images to be flipped back
            //first card flipped
            if(x1 == 0){
                Card1.setIcon(back);
            }
            else if (x1 == 1){
                Card2.setIcon(back);
            }
            else if (x1 == 2){
                Card3.setIcon(back);
            }
            else if (x1 == 3){
                Card4.setIcon(back);
            }
            else if (x1 == 4){
                Card5.setIcon(back);
            }
            else if (x1 == 5){
                Card6.setIcon(back);
            }
            else if (x1 == 6){
                Card7.setIcon(back);
            }
            else if (x1 == 7){
                Card8.setIcon(back);
            }
            else if (x1 == 8){
                Card9.setIcon(back);
            }
            else if (x1 == 9){
                Card10.setIcon(back);
            }
            else if (x1 == 10){
                Card11.setIcon(back);
            }
            else if (x1 == 11) {
                Card12.setIcon(back);
            }
            else if (x1 == 12) {
                Card13.setIcon(back);
            }
            else if (x1 == 13) {
                Card14.setIcon(back);
            }
            else if (x1 == 14) {
                Card15.setIcon(back);
            }
            else if (x1 == 15) {
                Card16.setIcon(back);
            }
            else if (x1 == 16) {
                Card17.setIcon(back);
            }
            else if (x1 == 17) {
                Card18.setIcon(back);
            }
            else if (x1 == 18) {
                Card19.setIcon(back);
            }
            else if (x1 == 19) {
                Card20.setIcon(back);
            }
            
            //second card flipped
            if(x2 == 0){
                Card1.setIcon(back);
            }
            else if (x2 == 1){
                Card2.setIcon(back);
            }
            else if (x2 == 2){
                Card3.setIcon(back);
            }
            else if (x2 == 3){
                Card4.setIcon(back);
            }
            else if (x2 == 4){
                Card5.setIcon(back);
            }
            else if (x2 == 5){
                Card6.setIcon(back);
            }
            else if (x2 == 6){
                Card7.setIcon(back);
            }
            else if (x2 == 7){
                Card8.setIcon(back);
            }
            else if (x2 == 8){
                Card9.setIcon(back);
            }
            else if (x2 == 9){
                Card10.setIcon(back);
            }
            else if (x2 == 10){
                Card11.setIcon(back);
            }
            else if (x2 == 11) {
                Card12.setIcon(back);
            }
            else if (x2 == 12) {
                Card13.setIcon(back);
            }
            else if (x2 == 13) {
                Card14.setIcon(back);
            }
            else if (x2 == 14) {
                Card15.setIcon(back);
            }
            else if (x2 == 15) {
                Card16.setIcon(back);
            }
            else if (x2 == 16) {
                Card17.setIcon(back);
            }
            else if (x2 == 17) {
                Card18.setIcon(back);
            }
            else if (x2 == 18) {
                Card19.setIcon(back);
            }
            else if (x2 == 19) {
                Card20.setIcon(back);
            }
            
            /*Change the card indexes to hidden*/
            change[x1] = 1;
            change[x2] = 1;
            
        }
        
        count = 0; //reset the number of cards flipped
    }//GEN-LAST:event_btnGuessAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatchingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Card1;
    private javax.swing.JButton Card10;
    private javax.swing.JButton Card11;
    private javax.swing.JButton Card12;
    private javax.swing.JButton Card13;
    private javax.swing.JButton Card14;
    private javax.swing.JButton Card15;
    private javax.swing.JButton Card16;
    private javax.swing.JButton Card17;
    private javax.swing.JButton Card18;
    private javax.swing.JButton Card19;
    private javax.swing.JButton Card2;
    private javax.swing.JButton Card20;
    private javax.swing.JButton Card3;
    private javax.swing.JButton Card4;
    private javax.swing.JButton Card5;
    private javax.swing.JButton Card6;
    private javax.swing.JButton Card7;
    private javax.swing.JButton Card8;
    private javax.swing.JButton Card9;
    private javax.swing.JMenu EditOption;
    private javax.swing.JMenu FileOption;
    private javax.swing.JMenu HelpOption;
    private javax.swing.JTextField Instructions;
    private javax.swing.JMenuBar TopMenu;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuessAgain;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel mainTitle;
    // End of variables declaration//GEN-END:variables
}
